export const GET_JADWAL_UJIAN = "GET_JADWAL_UJIAN";
export const GET_DETAIL_JADWAL_UJIAN = "GET_DETAIL_JADWAL_UJIAN";
export const GET_SOAL_UJIAN = "GET_SOAL_UJIAN";
export const GET_ONE_SOAL_UJIAN = "GET_ONE_SOAL_UJIAN";
export const SET_FORM_HASIL_UJIAN = "SET_FORM_HASIL_UJIAN";
export const GET_HASIL_UJIAN = "GET_HASIL_UJIAN";
